# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/core/
      - eng/
      - build.gradle
      - gradle.properties
      - settings.gradle

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/core/
      - eng/
      - build.gradle
      - gradle.properties
      - settings.gradle

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: template
      Artifacts:
        - name: azure-sdk-template
          safeName: azurecorecredential
          groupId: com.azure.android
