parameters:
  ServiceDirectory: not-specified # Set a default that breaks in obvious ways.
  Artifacts: []

jobs:
  - job: 'Build'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: sudo chmod -R go+w $ANDROID_HOME
        displayName: Make Android SDK directory writable
      - task: Gradle@2
        inputs:
          tasks: 'sdk:${{parameters.ServiceDirectory}}:publish'
          publishJUnitResults: false
        displayName: Build and publish
      - pwsh: |
          Get-ChildItem sdk/${{parameters.ServiceDirectory}}/**/repo -Attributes Directory -Recurse |
          ForEach-Object {
            $Source = $_.FullName + '/*'
            $Dest = '$(Build.ArtifactStagingDirectory)/' + $_.Parent.Parent.Name + '.zip'
            Write-Host "Compressing $Source to $Dest"
            Compress-Archive -Path $Source -DestinationPath $Dest
          }
        displayName: Stage artifacts for upload
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: packages
        displayName: Upload artifacts

  - job: 'Analyze'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: sudo chmod -R go+w $ANDROID_HOME
        displayName: Make Android SDK directory writable
      - task: Gradle@2
        inputs:
          tasks: 'sdk:${{parameters.ServiceDirectory}}:build'
          publishJUnitResults: false
          checkStyleRunAnalysis: true
          findBugsRunAnalysis: false # Install findbugs plugin before enabling
          pmdRunAnalysis: true
        displayName: Build and analyze
