parameters:
  ServiceDirectory: not-specified # Set a default that breaks in obvious ways.
  Artifacts: []

jobs:
  - job: 'Build'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: sudo chmod -R go+w $ANDROID_HOME
        displayName: Make Android SDK directory writable
      - task: Gradle@2
        inputs:
          tasks: 'sdk:${{parameters.ServiceDirectory}}:publish'
          publishJUnitResults: false
        displayName: Build and publish

      - ${{ each artifact in parameters.Artifacts }}:
        - pwsh: |
            $artifactsToStage = Get-ChildItem sdk/${{parameters.ServiceDirectory}}/${{artifact.name}}/build/repo/**/${{artifact.name}}* -Recurse | Where-Object -FilterScript { $_.Name -match "(jar|pom|aar|module)$" }
            $stagingLocation = New-Item -Type Directory -Path $(Build.ArtifactStagingDirectory) -Name ${{artifact.name}}
            $artifactsToStage | Copy-Item -Destination $stagingLocation
          displayName: Stage ${{artifact.name}} for upload

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: packages
        displayName: Upload artifacts

  - job: 'Analyze'

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: sudo chmod -R go+w $ANDROID_HOME
        displayName: Make Android SDK directory writable
      - task: Gradle@2
        inputs:
          tasks: 'sdk:${{parameters.ServiceDirectory}}:build'
          publishJUnitResults: false
          checkStyleRunAnalysis: true
          findBugsRunAnalysis: false # Install findbugs plugin before enabling
          pmdRunAnalysis: true
        displayName: Build and analyze
