resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
      ref: refs/tags/azure-sdk-build-tools_20211215.1

    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

parameters:
  Artifacts: []
  ServiceDirectory: not-specified

stages:
  - stage: Build
    jobs:
    - template: ../jobs/archetype-sdk-client.yml
      parameters:
        ServiceDirectory: ${{parameters.ServiceDirectory}}
        Artifacts: ${{parameters.Artifacts}}

  # The Prerelease and Release stages are conditioned on whether we are building a pull request and the branch.
  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
    - template: archetype-android-release.yml
      parameters:
        DependsOn: Build
        Artifacts: ${{parameters.Artifacts}}
        ArtifactName: packages
        VerifyVersions: 'false'